"use client";
import {useEffect,useRef,useState} from 'react';
import {DEFAULT_HUD_SKILLS,MAX_DASHBOARD_SKILLS} from '../../obsidian-v2/shared/dashboard.mjs';
import {dashboardDiscoveryNotice,dashboardIds,dashboardSkillsStore,moveDashboardSkill,skillUnavailable,toggleDashboardSkill,type DashboardProvider,type DashboardSnapshot,type DiscoveredSkill} from '@/lib/dashboard-skills';

export type DashboardEditorActions=Pick<typeof dashboardSkillsStore,'save'|'register'|'discover'|'refresh'>;
export default function DashboardCustomizer({data,provider,onClose,actions=dashboardSkillsStore}:{data:DashboardSnapshot;provider:DashboardProvider;onClose:()=>void;actions?:DashboardEditorActions}){
  const dialog=useRef<HTMLDialogElement>(null);
  const [revision,setRevision]=useState(data.revision),[draft,setDraft]=useState<string[]|null>(()=>data.selected===null?null:dashboardIds(data));
  const [query,setQuery]=useState(''),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false);
  const [found,setFound]=useState<DiscoveredSkill[]|null>(null),[discoveryProvider,setDiscoveryProvider]=useState(provider),[skillPath,setSkillPath]=useState('');
  useEffect(()=>{const element=dialog.current,previous=document.activeElement as HTMLElement|null;element?.showModal();element?.querySelector<HTMLInputElement>('input')?.focus();return()=>{element?.close();previous?.focus()}},[]);
  const ids=draft??[...DEFAULT_HUD_SKILLS],stale=revision!==data.revision;
  const matches=data.catalog.filter(skill=>`${skill.id} ${skill.label} ${skill.description}`.toLowerCase().includes(query.trim().toLowerCase()));
  const toggle=(id:string)=>{try{setDraft(toggleDashboardSkill(ids,id));setError('');setNotice('')}catch(e){setError(String((e as Error).message))}};
  const reload=()=>{setRevision(data.revision);setDraft(data.selected===null?null:dashboardIds(data));setError('');setNotice('Loaded the latest saved dashboard.')};
  const save=async()=>{setBusy(true);setError('');try{await actions.save(revision,draft);onClose()}catch(e){setError((e as Error).message);void actions.refresh()}finally{setBusy(false)}};
  const discover=async()=>{setBusy(true);setError('');setNotice('');try{const result=await actions.discover(discoveryProvider);if(result.error)throw new Error(result.error);setFound(result.skills);setNotice(dashboardDiscoveryNotice(result))}catch(e){setError((e as Error).message)}finally{setBusy(false)}};
  const register=async(skill:Pick<DiscoveredSkill,'path'|'providers'> & {label?:string})=>{setBusy(true);setError('');try{const result=await actions.register(revision,skill);setRevision(result.revision);setDraft(ids.includes(result.registeredId)?ids:ids.length<MAX_DASHBOARD_SKILLS?[...ids,result.registeredId]:ids);setNotice(ids.length>=MAX_DASHBOARD_SKILLS?'Registered. Remove a dashboard button to make room, then select this skill.':'Registered and selected. Save dashboard to keep your button choices.');setSkillPath('')}catch(e){setError((e as Error).message);void actions.refresh()}finally{setBusy(false)}};
  return <dialog ref={dialog} className="skill-browser dashboard-customizer" aria-labelledby="dashboard-customizer-title" onCancel={e=>{e.preventDefault();if(!busy)onClose()}}>
    <header><div><h2 id="dashboard-customizer-title">Your dashboard</h2><p>Choose up to {MAX_DASHBOARD_SKILLS} shortcuts. Your choices appear in Jarvis and Obsidian.</p></div><button disabled={busy} onClick={onClose} aria-label="Close dashboard customization">×</button></header>
    {stale&&<p className="dashboard-feedback" role="alert">The dashboard changed elsewhere. Load the latest choices before saving. <button disabled={busy} onClick={reload}>Load latest choices</button></p>}
    {data.error&&<p className="dashboard-feedback" role="alert">{data.error}</p>}
    <section aria-label="Selected dashboard skills"><div className="skill-browser-meta"><span>Selected: {ids.length} / {MAX_DASHBOARD_SKILLS}</span><span>{draft===null?'Default shortcuts':'Your shortcuts'}</span></div>
      <ol className="dashboard-selected">{ids.map((id,index)=>{const skill=data.catalog.find(item=>item.id===id),label=skill?.label||id;return <li key={id}><span>{label}{skill&&skillUnavailable(skill,provider,data.installedProviders)&&<small>{skillUnavailable(skill,provider,data.installedProviders)}</small>}{!skill&&<small>Skill unavailable</small>}</span><div><button disabled={busy||index===0} aria-label={`Move ${label} up`} onClick={()=>setDraft(moveDashboardSkill(ids,id,-1))}>↑</button><button disabled={busy||index===ids.length-1} aria-label={`Move ${label} down`} onClick={()=>setDraft(moveDashboardSkill(ids,id,1))}>↓</button><button disabled={busy} aria-label={`Remove ${label}`} onClick={()=>toggle(id)}>×</button></div></li>})}</ol>
      {!ids.length&&<p className="dashboard-note">No shortcuts selected. You can still use Browse all skills.</p>}
    </section>
    <label className="skill-search"><span>Search</span><input aria-label="Find dashboard skills" type="search" placeholder="Research, planning, content…" value={query} onChange={e=>setQuery(e.target.value)}/></label>
    <div className="dashboard-catalog">{matches.map(skill=><label key={skill.id} className="dashboard-choice"><input type="checkbox" checked={ids.includes(skill.id)} disabled={busy||(!ids.includes(skill.id)&&(!skill.available||ids.length>=MAX_DASHBOARD_SKILLS))} onChange={()=>toggle(skill.id)}/><span><strong>{skill.label}</strong><small>{skill.description}</small><small>{skill.kind==='installed'?'Installed · opens in a terminal':'Bundled workflow'} · {skill.providers.map(p=>p==='claude'?'Claude Code':'Codex').join(' / ')}</small>{skillUnavailable(skill,provider,data.installedProviders)&&<small className="dashboard-unavailable">{skillUnavailable(skill,provider,data.installedProviders)}</small>}</span></label>)}{!matches.length&&<p className="dashboard-note">No matching skills.</p>}</div>
    <details className="dashboard-discovery"><summary>Add your installed skills</summary><p>Find skills already installed for your coding tool, then register the ones you want. Registration adds a skill to the shared catalog immediately; button choices are saved below.</p>
      <div className="dashboard-discovery-actions"><label>Coding tool <select aria-label="Coding tool for installed skills" disabled={busy} value={discoveryProvider} onChange={e=>{setDiscoveryProvider(e.target.value as DashboardProvider);setFound(null);setNotice('')}}><option value="codex">Codex</option><option value="claude">Claude Code</option></select></label><button disabled={busy||stale} onClick={()=>void discover()}>Find my installed skills</button></div>
      {found&&<div className="dashboard-found">{found.map(skill=><div key={skill.path}><span><strong>{skill.label}</strong><small>{skill.description}</small><small>{skill.path}</small></span><button disabled={busy||stale} onClick={()=>void register(skill)}>Register & select</button></div>)}{!found.length&&<p>No skills found for this tool. You can enter the full path below.</p>}</div>}
      <form onSubmit={e=>{e.preventDefault();if(skillPath.trim())void register({path:skillPath.trim(),providers:[discoveryProvider]})}}><label>Or enter the full path to SKILL.md<input aria-label="Installed SKILL.md path" value={skillPath} onChange={e=>setSkillPath(e.target.value)} placeholder="Full path to an existing SKILL.md" disabled={busy}/></label><button disabled={busy||stale||!skillPath.trim()} type="submit">Register & select</button></form>
    </details>
    {error&&<p className="dashboard-feedback" role="alert">{error}</p>}{notice&&<p className="dashboard-note" role="status">{notice}</p>}
    <footer className="dashboard-editor-footer"><button disabled={busy} onClick={()=>{setDraft(null);setError('');setNotice('Default shortcuts selected. Save to apply; Obsidian also returns to its default shortcuts.')}}>Restore defaults</button><div><button disabled={busy} onClick={onClose}>Cancel</button><button className="dashboard-save" disabled={busy||stale} onClick={()=>void save()}>{busy?'Working…':'Save dashboard'}</button></div></footer>
  </dialog>;
}
