import test,{after} from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';import os from 'node:os';import crypto from 'node:crypto';import {build} from 'esbuild';
import {routeVoice,parseRoute,enqueue} from '../runner/bridge-core.mjs';import {writeJson,atomicRename} from '../runner/core.mjs';
import {commandFor} from '../runner/adapters.mjs';
const chosen={provider:'codex',model:'gpt-6-astra'};
test('Tier 1 direct commands do not require or call a model',async()=>{const root=vault();const r=await routeVoice(root,{id:crypto.randomUUID(),selection:chosen,transcript:'Is the worker online?'},new AbortController().signal,async()=>assert.fail('model should not be called'),null,{resolveCli:()=>null});assert.equal(r.tier,1);assert.equal(r.model,null);assert.equal(r.queued,null)});
test('Tier 2 stays on Luna despite old voice configuration',async()=>{const root=vault();writeJson(root,'system/v2/voice-config.json',{codex:'gpt-6-astra',claude:'opus'});const r=await routeVoice(root,{id:crypto.randomUUID(),selection:chosen,transcript:'What did the saved research recommend for our next project?'},new AbortController().signal,async(_root,j)=>{assert.equal(j.model,'gpt-5.6-luna');return{text:'{"action":"reply","reply":"Hello!"}'}});assert.equal(r.tier,2);assert.equal(r.workerModel,null);assert.equal(r.queued,null)});
test('Tier 3 uses Astra medium even if the manual worker selector is Luna',async()=>{const root=vault(),id=crypto.randomUUID();const r=await routeVoice(root,{id,selection:{provider:'codex',model:'gpt-5.6-luna'},transcript:'Could you please plan my day using my existing commitments?'},new AbortController().signal,async()=>({text:'{"action":"task","skill":"plan-today","reply":"Okay"}'}));assert.equal(r.tier,3);assert.equal(r.model,'gpt-5.6-luna');assert.equal(r.workerModel,'gpt-6-astra');const job=JSON.parse(fs.readFileSync(path.join(root,`system/v2/queue/${id}.json`)));assert.equal(job.reasoning_effort,'medium');assert.ok(commandFor(root,job).args.includes('model_reasoning_effort="medium"'));assert.equal(r.requestedWorkerModel,'gpt-5.6-luna')});
test('Windows sharing violations retry atomic replacement without deleting the target',()=>{let attempts=0;atomicRename('source','target',(a,b)=>{assert.equal(a,'source');assert.equal(b,'target');if(++attempts<3)throw Object.assign(new Error('sharing violation'),{code:'EPERM'})});assert.equal(attempts,3);assert.throws(()=>atomicRename('source','target',()=>{throw Object.assign(new Error('missing source'),{code:'ENOENT'})}),/missing source/)});
const vaults=[];after(()=>{for(const root of vaults)fs.rmSync(root,{recursive:true,force:true})});
function vault(){const root=fs.mkdtempSync(path.join(os.tmpdir(),'v2-voice-'));vaults.push(root);writeJson(root,'system/v2/runner-status.json',{ts:new Date().toISOString(),busy:false,providers:{codex:{installed:true}}});return root}
test('router rejects unsupported actions, bad JSON and oversized answers',()=>{assert.throws(()=>parseRoute('{'));assert.throws(()=>parseRoute(JSON.stringify({action:'shell',reply:'ok'})));assert.throws(()=>parseRoute(JSON.stringify({action:'task',skill:'send-email',reply:'ok'})));assert.throws(()=>parseRoute(JSON.stringify({action:'reply',reply:'x'.repeat(801)})))});
test('voice snapshots provider and worker model, uses fast model, queues only once',async()=>{
 const root=vault(),id=crypto.randomUUID();const response=await routeVoice(root,{id,selection:chosen,transcript:'Summarize my vault'},new AbortController().signal,async(_root,j,p)=>{
  assert.equal(j.provider,'codex');assert.equal(j.model,'gpt-5.6-luna');writeJson(root,'system/v2/provider.json',{provider:'claude',model:'sonnet'});return {text:'{"action":"task","skill":"vault-summary","reply":"Okay."}'};
 });
 assert.equal(response.queued,id);assert.equal(response.provider,'codex');const job=JSON.parse(fs.readFileSync(path.join(root,`system/v2/queue/${id}.json`)));assert.equal(job.model,'gpt-6-astra');
 enqueue(root,'vault-summary',chosen,id);assert.equal(fs.readdirSync(path.join(root,'system/v2/queue')).length,1);
});
test('cancel before routing completes cannot enqueue a task',async()=>{const root=vault(),controller=new AbortController();await assert.rejects(()=>routeVoice(root,{id:crypto.randomUUID(),selection:chosen,transcript:'Could you please plan today using my existing commitments?'},controller.signal,async()=>{controller.abort();return{text:'{"action":"task","skill":"plan-today","reply":"Okay"}'}}),/cancelled/);assert.equal(fs.existsSync(path.join(root,'system/v2/queue')),false)});
test('model errors and missing CLI never fall back',async()=>{const root=vault();let calls=0;await assert.rejects(()=>routeVoice(root,{id:crypto.randomUUID(),selection:chosen,transcript:'What did the saved research recommend for our next project?'},new AbortController().signal,async()=>{calls++;throw new Error('model unavailable')},null,{resolveCli:()=>({command:'fake-codex',prefix:[]})}),/model unavailable/);assert.equal(calls,1);await assert.rejects(()=>routeVoice(root,{id:crypto.randomUUID(),selection:chosen,transcript:'What did the saved research recommend for our next project?'},new AbortController().signal,async()=>{calls++},null,{resolveCli:()=>null}),/not installed/);assert.equal(calls,1)});
const bundle=await build({entryPoints:['shared/voice-session.ts'],bundle:true,platform:'node',format:'esm',write:false});
const {VoiceSession}=await import('data:text/javascript;base64,'+Buffer.from(bundle.outputFiles[0].text).toString('base64'));
test('late reply after interruption cannot play audio or surface stale response',async()=>{
 let finish,returned=false,speaks=0;const transport=async(p)=>{if(p==='/voice/text')return new Promise(r=>finish=r);if(p==='/voice/speak')speaks++;return {status:200,json:{ok:true}}};
 const voice=new VoiceSession(transport,async()=>chosen);voice.onReply=()=>returned=true;
 const pending=voice.sendText('Hello');await new Promise(r=>setImmediate(r));voice.cancel();finish({status:200,json:{reply:'Late reply'}});await pending;
 assert.equal(returned,false);assert.equal(speaks,0);assert.equal(voice.mode,'idle');await voice.destroy();
});
test('late microphone permission after cancellation releases stream',async()=>{
 const previous=Object.getOwnPropertyDescriptor(globalThis,'navigator'),rec=globalThis.MediaRecorder;let grant,stopped=0;
 Object.defineProperty(globalThis,'navigator',{configurable:true,value:{mediaDevices:{getUserMedia:()=>new Promise(r=>grant=r)}}});globalThis.MediaRecorder=class{};
 try{const voice=new VoiceSession(async()=>({status:200,json:{ok:true}}),async()=>chosen);const pending=voice.start();await new Promise(r=>setImmediate(r));voice.cancel();grant({getTracks:()=>[{stop:()=>stopped++}]});await pending;assert.equal(stopped,1);assert.equal(voice.mode,'idle');await voice.destroy()}
 finally{if(previous)Object.defineProperty(globalThis,'navigator',previous);else delete globalThis.navigator;globalThis.MediaRecorder=rec}
});
